# Observability increment (#181): 3 CloudWatch alarms + 1 dashboard, notifying
# via the account stack's persistent SNS topic. No Container Insights, no
# custom metrics, no log-based metric filters (spec §4.5, out of scope).

locals {
  sns_topic_arn = data.terraform_remote_state.account.outputs.sns_topic_arn
}

# Maximum (not Minimum) on HealthyHostCount: "< 1" only fires once every
# ALB node agrees there are zero healthy targets, so a single node's
# transient, out-of-sync reading during normal reporting doesn't trip the
# alarm. treat_missing_data = "breaching" because desired_count = 1 gives
# this service no redundancy - a gap in reporting (deregistered target) is
# itself a potential outage, not a state to hide. The 5x60s window absorbs a
# normal rolling deployment (deployment_min/max_percent = 100/200 keeps the
# old task alive until the new one is healthy, see services.tf), so only a
# sustained, real loss of healthy targets crosses it. Intentionally scaling
# desired_count to 0 (without destroying the stack) will trip this alarm -
# accepted, since the alarm itself stays alive in that case.
resource "aws_cloudwatch_metric_alarm" "frontend_healthy_host" {
  alarm_name          = "${local.name_prefix}-frontend-healthy-host"
  alarm_description   = "Frontend target group reports zero healthy targets on every ALB node for 5 consecutive minutes."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HealthyHostCount"
  statistic           = "Maximum"
  period              = 60
  threshold           = 1
  comparison_operator = "LessThanThreshold"
  evaluation_periods  = 5
  datapoints_to_alarm = 5
  treat_missing_data  = "breaching"

  dimensions = {
    LoadBalancer = aws_lb.this.arn_suffix
    TargetGroup  = aws_lb_target_group.frontend.arn_suffix
  }

  alarm_actions             = [local.sns_topic_arn]
  ok_actions                = [local.sns_topic_arn]
  insufficient_data_actions = []

  tags = local.common_tags
}

resource "aws_cloudwatch_metric_alarm" "backend_healthy_host" {
  alarm_name          = "${local.name_prefix}-backend-healthy-host"
  alarm_description   = "Backend target group reports zero healthy targets on every ALB node for 5 consecutive minutes."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HealthyHostCount"
  statistic           = "Maximum"
  period              = 60
  threshold           = 1
  comparison_operator = "LessThanThreshold"
  evaluation_periods  = 5
  datapoints_to_alarm = 5
  treat_missing_data  = "breaching"

  dimensions = {
    LoadBalancer = aws_lb.this.arn_suffix
    TargetGroup  = aws_lb_target_group.backend.arn_suffix
  }

  alarm_actions             = [local.sns_topic_arn]
  ok_actions                = [local.sns_topic_arn]
  insufficient_data_actions = []

  tags = local.common_tags
}

# ALB-level (LoadBalancer dimension only, not per target group): covers 5xx
# responses generated by either target behind this ALB, matching the #181
# issue's single "ALB target 5xx alarm" scope. Does not cover
# HTTPCode_ELB_5XX_Count (errors generated by the ALB itself), which is a
# separate metric and out of this alarm's scope. Sum because the metric is a
# count (Minimum/Maximum/Average all report 1, per AWS docs);
# treat_missing_data = "notBreaching" because this metric only publishes a
# datapoint on a nonzero value - no data means no 5xx, not a gap to worry
# about (opposite semantics from the healthy-host alarms above).
resource "aws_cloudwatch_metric_alarm" "alb_target_5xx" {
  alarm_name          = "${local.name_prefix}-alb-target-5xx"
  alarm_description   = "5 or more HTTP 5xx responses from targets behind the ALB within a 5-minute window."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  statistic           = "Sum"
  period              = 300
  threshold           = 5
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 1
  datapoints_to_alarm = 1
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = aws_lb.this.arn_suffix
  }

  alarm_actions             = [local.sns_topic_arn]
  ok_actions                = [local.sns_topic_arn]
  insufficient_data_actions = []

  tags = local.common_tags
}

# One concise, single-screen dashboard (2 columns x 3 rows). Frontend/backend
# pairs share a widget (CPU, Memory, HealthyHostCount) to keep the widget
# count low. HealthyHostCount uses Maximum here too, so the dashboard reads
# consistently with what the alarms above actually trigger on.
resource "aws_cloudwatch_dashboard" "this" {
  dashboard_name = "${local.name_prefix}-observability"

  dashboard_body = jsonencode({
    widgets = [
      {
        type   = "metric"
        x      = 0
        y      = 0
        width  = 12
        height = 6
        properties = {
          title  = "ECS CPU Utilization"
          view   = "timeSeries"
          region = var.aws_region
          stat   = "Average"
          period = 300
          metrics = [
            ["AWS/ECS", "CPUUtilization", "ClusterName", aws_ecs_cluster.this.name, "ServiceName", module.frontend.service_name, { label = "frontend" }],
            ["AWS/ECS", "CPUUtilization", "ClusterName", aws_ecs_cluster.this.name, "ServiceName", module.backend.service_name, { label = "backend" }],
          ]
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 0
        width  = 12
        height = 6
        properties = {
          title  = "ECS Memory Utilization"
          view   = "timeSeries"
          region = var.aws_region
          stat   = "Average"
          period = 300
          metrics = [
            ["AWS/ECS", "MemoryUtilization", "ClusterName", aws_ecs_cluster.this.name, "ServiceName", module.frontend.service_name, { label = "frontend" }],
            ["AWS/ECS", "MemoryUtilization", "ClusterName", aws_ecs_cluster.this.name, "ServiceName", module.backend.service_name, { label = "backend" }],
          ]
        }
      },
      {
        type   = "metric"
        x      = 0
        y      = 6
        width  = 12
        height = 6
        properties = {
          title  = "ALB Request Count"
          view   = "timeSeries"
          region = var.aws_region
          stat   = "Sum"
          period = 300
          metrics = [
            ["AWS/ApplicationELB", "RequestCount", "LoadBalancer", aws_lb.this.arn_suffix],
          ]
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 6
        width  = 12
        height = 6
        properties = {
          title  = "ALB Target Response Time"
          view   = "timeSeries"
          region = var.aws_region
          stat   = "Average"
          period = 300
          metrics = [
            ["AWS/ApplicationELB", "TargetResponseTime", "LoadBalancer", aws_lb.this.arn_suffix],
          ]
        }
      },
      {
        type   = "metric"
        x      = 0
        y      = 12
        width  = 12
        height = 6
        properties = {
          title  = "ALB Target 5xx"
          view   = "timeSeries"
          region = var.aws_region
          stat   = "Sum"
          period = 300
          metrics = [
            ["AWS/ApplicationELB", "HTTPCode_Target_5XX_Count", "LoadBalancer", aws_lb.this.arn_suffix],
          ]
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 12
        width  = 12
        height = 6
        properties = {
          title  = "Target Group Healthy Hosts"
          view   = "timeSeries"
          region = var.aws_region
          stat   = "Maximum"
          period = 300
          metrics = [
            ["AWS/ApplicationELB", "HealthyHostCount", "LoadBalancer", aws_lb.this.arn_suffix, "TargetGroup", aws_lb_target_group.frontend.arn_suffix, { label = "frontend" }],
            ["AWS/ApplicationELB", "HealthyHostCount", "LoadBalancer", aws_lb.this.arn_suffix, "TargetGroup", aws_lb_target_group.backend.arn_suffix, { label = "backend" }],
          ]
        }
      },
    ]
  })
}
