name: CI

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  backend-build:
    name: Backend build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        run: npm install

      - name: Build backend
        run: npm run build

  frontend-build:
    name: Frontend build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

  terraform-foundation-validate:
    name: Terraform foundation validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10.0"
          terraform_wrapper: false

      - name: Terraform fmt check (foundation)
        run: terraform fmt -check -recursive infra/terraform/foundation

      - name: Terraform fmt check (modules/network)
        run: terraform fmt -check -recursive infra/terraform/modules/network

      - name: Terraform fmt check (modules/ecr-repository)
        run: terraform fmt -check -recursive infra/terraform/modules/ecr-repository

      - name: Terraform init (foundation, no backend)
        run: terraform -chdir=infra/terraform/foundation init -backend=false -lockfile=readonly

      - name: Terraform validate (foundation)
        run: terraform -chdir=infra/terraform/foundation validate

  terraform-data-validate:
    name: Terraform data validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10.0"
          terraform_wrapper: false

      - name: Terraform fmt check (data)
        run: terraform fmt -check -recursive infra/terraform/data

      - name: Terraform init (data, no backend)
        run: terraform -chdir=infra/terraform/data init -backend=false -lockfile=readonly

      - name: Terraform validate (data)
        run: terraform -chdir=infra/terraform/data validate
